import React, { useState } from "react";

import type { NextPage } from "next";
import Head from "next/head";

import Initial from "../components/Initial";
import Quiz from "../components/Quiz";
import Progress from "../components/Progress";
import Results from "../components/Results";
import Footer from "../components/Footer";
import Settings from "../components/Settings";

import useAppContext from "../context/useContext";

const Home: NextPage = () => {
  const {
    state: { initialized, restart },
  } = useAppContext();
  const [isSelected, setIsSelected] = useState(false);
  const initializedModifier = initialized ? "quiz-modal--initialized" : "";

  return (
    <div>
      <Head>
        <title>Quiz Time | Jordan Utz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`quiz-modal ${initializedModifier}`}>
        {/* If application is not initialized and currentIndex is not set, render Initial. */}

        {!initialized && !restart && (
          <>
            <Initial />
            <Footer modifier="quiz-modal__footer--bg">
              <Settings />
            </Footer>
          </>
        )}

        {/* If application is initialized, render Quiz. */}
        {initialized && (
          <>
            <Quiz isSelected={isSelected} setIsSelected={setIsSelected} />
            <Footer>
              <Progress isSelected={isSelected} setIsSelected={setIsSelected} />
            </Footer>
          </>
        )}

        {/* If application is initialized, questions have been set, and the user has reached the end of the question set, render Results. */}
        {!initialized && restart && (
          <>
            <Results />
            <Footer modifier="quiz-modal__footer--bg">
              <Settings />
            </Footer>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
